### ISSUE TITLE
install error of cpp-ethereum

### ISSUE THREAD

**Issue by bezzangi** [ethereum/homebrew-ethereum#135] opened 2018-01-13 16:14 UTC
OS : OSX High Sierra 10.13.1

#brew install cpp-ethereum

==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/bezzangi/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/bezzangi/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:103 (hunter_add_package)

-- Configuring incomplete, errors occurred!

**Comment by boxofdeath** [comment] 2018-01-15 21:13
Same here on 10.13.2

**Comment by dukeblue2017** [comment] 2018-01-28 00:21
Same here, also 10.13.2

**Comment by trvstan** [comment] 2018-02-18 19:38
Same here, 10.13.3

**Comment by chfast** [comment] 2018-02-20 14:32
Duplicate of https://github.com/ethereum/homebrew-ethereum/issues/129.

**Closed** 2018-02-20 15:24 UTC
