### ISSUE TITLE
Homebrew formula missing "with-d-bus" for Qt dependency

### ISSUE THREAD

**Issue by stefanrenne** [ethereum/homebrew-ethereum#53] opened 2016-01-14 10:19 UTC
On OSX 10.11.2

When performing the install 
"brew install cpp-ethereum --with-gui" or dev reinstall "brew reinstall cpp-ethereum --devel --with-gui"

I see the following error:

==> Reinstalling ethereum/ethereum/cpp-ethereum with --with-gui
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/xyz/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
cmake
-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.0rc2
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DCMAKE_BUILD_TYPE=Release
-DEVMJIT=0
-DFATDB=1
-DGUI=1

CMake Error: The current CMakeCache.txt directory /tmp/cpp-ethereum20160114-69299-yhkixx/CMakeCache.txt is different than the directory /Library/Caches/Homebrew/cpp-ethereum--git where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/tmp/cpp-ethereum20160114-69299-yhkixx/CMakeLists.txt" does not match the source "/Library/Caches/Homebrew/cpp-ethereum--git/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues

**Comment by bobsummerwill** [comment] 2016-01-14 18:33
Hey @stefanrenne!

Homebrew is keeping us very busy with its delightfully behaviour.

What I would suggest is that you do the following:

    brew update
    brew upgrade
    brew uninstall cpp-ethereum
    rm -rf /Library/Caches/Homebrew/cpp-ethereum--git
    brew install cpp-ethereum --with-gui

It appears that Homebrew loves to screw its own internal state up based on past actions.    The caching it simply delightful.

Please could you give that a go and report back?   Thanks!

**Comment by stefanrenne** [comment] 2016-01-14 18:46
Hi Bob,

The command "brew uninstall cpp-ethereum"
Returned: "Error: No such keg: /usr/local/Cellar/cpp-ethereum"

I just ignored that and continued, at the point of install cpp-ethereum it failed with the following errors

==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Cloning into '/Library/Caches/Homebrew/cpp-ethereum--git'...
remote: Counting objects: 39, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 39 (delta 1), reused 25 (delta 1), pack-reused 0
Unpacking objects: 100% (39/39), done.
Checking connectivity... done.
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/310154512p/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  alethzero/libaleth/CMakeLists.txt:22 (eth_use)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum20160114-23226-uc12tc/CMakeFiles/CMakeOutput.log".
See also "/tmp/cpp-ethereum20160114-23226-uc12tc/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues

**Comment by bobsummerwill** [comment] 2016-01-14 18:57
Just want to verify that you are following the instructions at https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X?

You **will need** to do the shitty workarounds at the start of the document.   Looks like you've missed this one - https://github.com/ethereum/webthree-umbrella/wiki/QTBUG-50155-workaround, which again might need juicing up with some cache-busting.

**Comment by bobsummerwill** [comment] 2016-01-30 08:43
Hey @stefanrenne,
Lots of work has gone into this, and https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X is now hack-free.

Please could you have another try at this, starting from the start?    Thanks!

**Comment by nikhilshekhawat** [comment] 2016-02-02 20:04
Hi Bob,
Still the same issue:



 brew install cpp-ethereum --with-gui
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/phil/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    Qt5DBusConfig.cmake
    qt5dbus-config.cmake

  Add the installation prefix of "Qt5DBus" to CMAKE_PREFIX_PATH or set
  "Qt5DBus_DIR" to a directory containing one of the above files.  If
  "Qt5DBus" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  alethzero/libaleth/CMakeLists.txt:22 (eth_use)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum20160202-44771-1or8jo0/CMakeFiles/CMakeOutput.log".
See also "/tmp/cpp-ethereum20160202-44771-1or8jo0/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues

**Comment by nikhilshekhawat** [comment] 2016-02-02 20:50
even building from source fails
LLVM_DIR=/usr/local/Cellar/llvm/HEAD/share/llvm/cmake cmake ..
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- boost headers: /usr/local/include
-- boost lib   : /usr/local/lib/libboost_thread-mt.a;/usr/local/lib/libboost_date_time-mt.a;/usr/local/lib/libboost_system-mt.a;/usr/local/lib/libboost_regex-mt.a;/usr/local/lib/libboost_chrono-mt.a;/usr/local/lib/libboost_filesystem-mt.a;/usr/local/lib/libboost_unit_test_framework-mt.a;/usr/local/lib/libboost_program_options-mt.a;/usr/local/lib/libboost_random-mt.a

------------------------------------------------------------------------
-- Configuring cpp-ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.4.3
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- Found gmp: /usr/local/include  
-- Gmp headers: /usr/local/include
-- Gmp lib   : /usr/local/lib/libgmp.dylib

------------------------------------------------------------------------
-- Configuring dev
------------------------------------------------------------------------
--                  CMake Version                            3.4.3
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        ON
------------------------------------------------------------- components
-- GUI              Build GUI components                     ON
-- TESTS            Build tests                              ON
-- TOOLS            Build tools                              ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- Found jsoncpp: /usr/local/include  
-- JsonCpp headers: /usr/local/include
-- JsonCpp lib   : /usr/local/lib/libjsoncpp.dylib
-- Found leveldb: /usr/local/include  
-- LevelDB headers: /usr/local/include
-- LevelDB lib   : /usr/local/lib/libleveldb.dylib
-- Found CryptoPP: /usr/local/include (found suitable version "5.6.3", minimum required is "5.6.2") 
-- CryptoPP headers: /usr/local/include
-- CryptoPP lib   : /usr/local/lib/libcryptopp.a
-- Found miniupnpc: /usr/local/include  
-- miniupnpc headers: /usr/local/include
-- miniupnpc lib   : /usr/local/lib/libminiupnpc.dylib
./memorydb.cpp./overlaydb.cpp./test.cpp./libdevcore/./Base36.cpp./libdevcore/./CommonJS.cpp./libdevcore/./core.cpp./libdevcore/./FixedHash.cpp./libdevcore/./RangeMask.cpp./libdevcore/./rlp.cpp./libdevcrypto/./AES.cpp./libdevcrypto/./crypto.cpp./libdevcrypto/./hexPrefix.cpp./libdevcrypto/./MemTrie.cpp./libdevcrypto/./SecretStore.cpp./libdevcrypto/./trie.cpp./libp2p/./capability.cpp./libp2p/./net.cpp./libp2p/./peer.cpp./libp2p/./rlpx.cpp

------------------------------------------------------------------------
-- Configuring ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.4.3
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
--                  Hardware identification support          
--                  HTTP Request support                     
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  ON
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- OLYMPIC          Default to the Olympic network           OFF
-- PARANOID         -                                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     ON
-- TESTS            Build tests                              ON
-- ETHASHCL         Build OpenCL components                  ON
-- EVMJIT           Build LLVM-based JIT EVM                 ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- Found LLVM 3.9.0svn
-- Using LLVMConfig.cmake in: /usr/local/opt/llvm/share/llvm/cmake
-- EVM JIT version: 0.9.0
-- Found json_rpc_cpp: /usr/local/include (found suitable version "0.6.0", minimum required is "0.4") 
-- json-rpc-cpp headers: /usr/local/include
-- json-rpc-cpp lib   : /usr/local/lib/libjsonrpccpp-common.dylib;/usr/local/lib/libjsonrpccpp-server.dylib;/usr/local/lib/libjsonrpccpp-client.dylib
-- Found CURL: /usr/include  
-- curl headers: /usr/include
-- curl lib   : /usr/lib/libcurl.dylib
-- Found mhd: /usr/local/include  
-- microhttpd headers: /usr/local/include
-- microhttpd lib   : /usr/local/lib/libmicrohttpd.dylib
-- jsonrpcstub location    : /usr/local/bin/jsonrpcstub
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework  
-- OpenCL headers: /System/Library/Frameworks/OpenCL.framework
-- OpenCL lib   : /System/Library/Frameworks/OpenCL.framework
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
-- test: JsonRpc |  --eth_testfile=BlockTests/bcJS_API_Test; --eth_testfile=BlockTests/bcValidBlockTest

------------------------------------------------------------------------
-- Configuring webthree
------------------------------------------------------------------------
--                  CMake Version                            3.4.3
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     ON
-- TESTS            Build tests                              ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

-- solidity headers: /Users/phil/Desktop/RBCprojects/ethereum/webthree-umbrella/solidity
-- solidity lib   : solidity
-- V8 headers: /usr/local/opt/v8-315/include
-- V8 lib   : /usr/local/opt/v8-315/lib/libv8.dylib
-- Found readline: /usr/local/Cellar/readline/6.3.8/include  
-- readline headers: /usr/local/Cellar/readline/6.3.8/include
-- readline lib   : /usr/local/Cellar/readline/6.3.8/lib/libreadline.dylib

------------------------------------------------------------------------
-- Configuring solidity
------------------------------------------------------------------------
--                  CMake Version                            3.4.3
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     ON
-- TESTS            Build tests                              ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------


------------------------------------------------------------------------
-- Configuring alethzero
------------------------------------------------------------------------
--                  CMake Version                            3.4.3
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Darwin
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     ON
-- SOLIDITY         Build Solidity                           ON
------------------------------------------------------------------------

CMake Error at webthree-helpers/cmake/UseQt.cmake:30 (find_package):
  By not providing "FindQt5DBus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5DBus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5DBus"
  (requested version 5.4) with any of the following names:

    Qt5DBusConfig.cmake
    qt5dbus-config.cmake

  Add the installation prefix of "Qt5DBus" to CMAKE_PREFIX_PATH or set
  "Qt5DBus_DIR" to a directory containing one of the above files.  If
  "Qt5DBus" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  alethzero/libaleth/CMakeLists.txt:22 (eth_use)


-- Configuring incomplete, errors occurred!
See also "/Users/phil/Desktop/RBCprojects/ethereum/webthree-umbrella/build/CMakeFiles/CMakeOutput.log".
See also "/Users/phil/Desktop/RBCprojects/ethereum/webthree-umbrella/build/CMakeFiles/CMakeError.log".

**Comment by bobsummerwill** [comment] 2016-02-06 17:13
#55 as reported by @HalfbakedFlunky looks to be failing in exactly the same way now, so merging issues.

**Comment by bobsummerwill** [comment] 2016-02-06 17:14
Hey guys ... normally I've been helping to troubleshoot OS X issues, but I'm on vacation right now.

Hope to grab some evening time soon to see if I can get you guys unstuck.

**Comment by bobsummerwill** [comment] 2016-02-06 17:23
I've uninstalled my Homebrew, and am doing a `brew install cpp-ethereum --with-gui` completely from scratch on my OS X 10.11.3, and we'll see if I can replicate the issue.

It sounds like it might be the case where, again, the rolling package manager has moved the ground underneath us, and broken what was previously working.

**Comment by bobsummerwill** [comment] 2016-02-07 01:23
Still working at this, but it seems the problem is really "simple", in that `brew install cpp-ethereum --with-gui" appears **not** to be chaining an install of Qt anymore, so the build just falls over based on that.

I'm going through the multi-hour process of a Qt install now, to verify that everything is fine when that is done.     Just re-added the `brew install qt5 --with-d-bus` line to the building from source instructions.   That had been removed when we had the compulsary Qt workaround, and I forgot to re-add it when the workaround was resolved.

Even if that gets that "working", we will still be left with the mystery of why the homebrew installation has become broken, and is failing to chain a Qt5 install.    It used it work.    Or maybe it has been broken for a VERY long time, and that was just being masked by the need for the workarounds to patch the bugs in the Q5 formula itself.

**Comment by bobsummerwill** [comment] 2016-02-08 02:26
OK ... I'm going insane trying to get Qt5 built on my Mac.    It is SO damn slow, taking 4-8 hours or so.   Have been running out of disk space, hitting weird build breaks and having to restart.

Looks like I am now just about there with `brew install qt5 --with-d-bus --without-webkit --verbose`.

I want to verify that `brew install cpp-ethereum` works with Qt5 already installed.    Still missing out on an understanding of why the declared dependency on Qt5 in the cpp-ethereum Formula isn't triggering the Qt5 install.

**Comment by bobsummerwill** [comment] 2016-02-08 02:54
See also https://github.com/ethereum/homebrew-ethereum/issues/52

**Comment by bobsummerwill** [comment] 2016-02-08 03:22
OK - I think that https://github.com/ethereum/homebrew-ethereum/pull/56 should address this.

@caktux Does this change make sense to you?    I think it has isolated the root cause, but I'm a Homebrew novice.

**Comment by bobsummerwill** [comment] 2016-02-13 17:14
Just waiting on https://github.com/ethereum/webthree-helpers/pull/86 to be merged.

**Comment by bobsummerwill** [comment] 2016-02-15 06:25
PR has been merged, but for some reason the Homebrew formula isn't showing as updated here.
Some issue with the automation.

**Comment by bobsummerwill** [comment] 2016-02-16 06:57
Fixed now as part of #57

**Closed by bobsummerwill** 2016-02-16 06:57 UTC
Labels: bug

**Comment by nikhilshekhawat** [comment] 2016-02-18 03:35
thanks for the help @bobsummerwill 
Setting up compiled binaries would be easier I guess instead of maintaining the entire dependency flow at different places.

**Comment by bobsummerwill** [comment] 2016-02-18 04:47
No problem.    Yes, getting things into a good state is providing quite a challenge, but I think we're just about there now.   Just some loose ends TODO.

**Comment by HalfbakedFlunky** [comment] 2016-02-19 03:36
Yes, thank you bob.  Much appreciated.

**Comment by bobsummerwill** [comment] 2016-02-19 15:22
no problem, @HalfbakedFlunky!
