### ISSUE TITLE
Error installing cpp-ethereum on OSX

### ISSUE THREAD

**Issue by nicexe** [ethereum/homebrew-ethereum#126] opened 2017-09-07 09:44 UTC
I attempted to build cpp-ethereum with homebrew using `brew install ethereum/ethereum/cpp-ethereum --successful --devel`
During the building process homebrew reported an error.

Here is the log: https://gist.github.com/nicexe/bb990d165ad54f19e5c821b03b3606a8

`brew config` gives this output:
```
HOMEBREW_VERSION: 1.3.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 751334a257d81851e68da7ab390982d4e9fdf909
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 09ea2f4132c81d2f67a5ebb236e12831476f5269
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.5.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_2/bin/ruby
Java: 1.8.0_20, 1.7.0_67, 1.6.0_65-b14-466.1
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11
```

**Comment by manshmedia** [comment] 2017-12-02 13:52
same problem here 

>CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:101 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171202-13131-d7pxi1/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126

**Comment by csinghdev** [comment] 2017-12-06 10:54
same issue
-------------
CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:101 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171206-39064-1lx7tr2/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124

**Comment by rainmetersjtu** [comment] 2017-12-18 14:20
get the exactly the same issue

**Comment by DaveLindberg** [comment] 2017-12-20 12:32
same issue, running Mac OS 10.13.2 High Sierra with a fresh Homebrew installation.
`brew install cpp-ethereum` 
produces:
`CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
.brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
.brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
.brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
.brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:103 (hunter_add_package)`

**Comment by clutchcoder** [comment] 2017-12-20 23:41
I got the same errors as above, and I noticed this is the error -

```
-- Found leveldb: /usr/local/lib/libleveldb.dylib  
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CryptoPP (missing: CRYPTOPP_INCLUDE_DIR CRYPTOPP_LIBRARY)
  (Required is at least version "5.6.2")
```

Looks like the maintainers of ethminer have added some dependencies that didnt get added to the brew install scripts.

I was able to install the dependency with this:

`brew install CryptoPP`

then re-install

`brew install ethereum/ethereum/cpp-ethereum --successful --devel`

**Comment by DaveLindberg** [comment] 2017-12-21 02:38
Confirmed @clutchcoder's installation of CryptoPP makes progress. Similar results:
```
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=
==> make
Last 15 lines from /Users/dlindberg/Library/Logs/Homebrew/cpp-ethereum/02.make:
[ 88%] Building CXX object test/libethereum/test/CMakeFiles/testeth.dir/libethereum/TransactionQueue.cpp.o
cd /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_AFTER_REPOSITORY_MERGE -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20171220-29061-naikzx -I/tmp/cpp-ethereum-20171220-29061-naikzx/include -isystem /usr/local/include -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../../utils -I/tmp/cpp-ethereum-20171220-29061-naikzx/evmjit/include  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/libethereum/TransactionQueue.cpp.o -c /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/libethereum/TransactionQueue.cpp
[ 89%] Building CXX object test/libethereum/test/CMakeFiles/testeth.dir/libethereum/TransactionTests.cpp.o
cd /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_AFTER_REPOSITORY_MERGE -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20171220-29061-naikzx -I/tmp/cpp-ethereum-20171220-29061-naikzx/include -isystem /usr/local/include -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../../utils -I/tmp/cpp-ethereum-20171220-29061-naikzx/evmjit/include  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/libethereum/TransactionTests.cpp.o -c /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/libethereum/TransactionTests.cpp
[ 89%] Building CXX object test/libethereum/test/CMakeFiles/testeth.dir/libweb3core/crypto.cpp.o
cd /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_AFTER_REPOSITORY_MERGE -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20171220-29061-naikzx -I/tmp/cpp-ethereum-20171220-29061-naikzx/include -isystem /usr/local/include -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../../utils -I/tmp/cpp-ethereum-20171220-29061-naikzx/evmjit/include  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/libweb3core/crypto.cpp.o -c /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/libweb3core/crypto.cpp
[ 90%] Building CXX object test/libethereum/test/CMakeFiles/testeth.dir/libevm/vm.cpp.o
cd /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_AFTER_REPOSITORY_MERGE -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20171220-29061-naikzx -I/tmp/cpp-ethereum-20171220-29061-naikzx/include -isystem /usr/local/include -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../../utils -I/tmp/cpp-ethereum-20171220-29061-naikzx/evmjit/include  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/libevm/vm.cpp.o -c /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/libevm/vm.cpp
[ 90%] Building CXX object test/libethereum/test/CMakeFiles/testeth.dir/external-dependencies/boost.cpp.o
cd /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DETH_AFTER_REPOSITORY_MERGE -DETH_ETHASHCL -DETH_EVMJIT -DETH_FATDB -DETH_FRONTIER -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/tmp/cpp-ethereum-20171220-29061-naikzx -I/tmp/cpp-ethereum-20171220-29061-naikzx/include -isystem /usr/local/include -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../.. -I/tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/../../../utils -I/tmp/cpp-ethereum-20171220-29061-naikzx/evmjit/include  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/testeth.dir/external-dependencies/boost.cpp.o -c /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test/external-dependencies/boost.cpp
[ 90%] Linking CXX executable testeth
cd /tmp/cpp-ethereum-20171220-29061-naikzx/test/libethereum/test && /usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/testeth.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -std=c++11 -fpermissive -O3 -DNDEBUG -DETH_RELEASE -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/testeth.dir/BlockChainHelper.cpp.o CMakeFiles/testeth.dir/Stats.cpp.o CMakeFiles/testeth.dir/TestHelper.cpp.o CMakeFiles/testeth.dir/TestUtils.cpp.o CMakeFiles/testeth.dir/boostTest.cpp.o CMakeFiles/testeth.dir/fuzzTesting/createRandomTest.cpp.o CMakeFiles/testeth.dir/fuzzTesting/fuzzHelper.cpp.o CMakeFiles/testeth.dir/libethcore/commonjs.cpp.o CMakeFiles/testeth.dir/libethcore/dagger.cpp.o CMakeFiles/testeth.dir/libethcore/difficulty.cpp.o CMakeFiles/testeth.dir/libethcore/icap.cpp.o CMakeFiles/testeth.dir/libethcore/keymanager.cpp.o CMakeFiles/testeth.dir/libethereum/AccountDiff.cpp.o CMakeFiles/testeth.dir/libethereum/Block.cpp.o CMakeFiles/testeth.dir/libethereum/BlockChain.cpp.o CMakeFiles/testeth.dir/libethereum/BlockChainInsert.cpp.o CMakeFiles/testeth.dir/libethereum/BlockChainTests.cpp.o CMakeFiles/testeth.dir/libethereum/BlockQueue.cpp.o CMakeFiles/testeth.dir/libethereum/ClientBase.cpp.o CMakeFiles/testeth.dir/libethereum/GasPricer.cpp.o CMakeFiles/testeth.dir/libethereum/Genesis.cpp.o CMakeFiles/testeth.dir/libethereum/State.cpp.o CMakeFiles/testeth.dir/libethereum/StateOriginal.cpp.o CMakeFiles/testeth.dir/libethereum/Transaction.cpp.o CMakeFiles/testeth.dir/libethereum/TransactionQueue.cpp.o CMakeFiles/testeth.dir/libethereum/TransactionTests.cpp.o CMakeFiles/testeth.dir/libweb3core/crypto.cpp.o CMakeFiles/testeth.dir/libevm/vm.cpp.o CMakeFiles/testeth.dir/external-dependencies/boost.cpp.o  -o testeth /usr/local/lib/libboost_unit_test_framework-mt.a libtestutils/libtestutils.dylib ../../../libethashseal/libethashseal.dylib ../../../libethereum/libethereum.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libboost_regex-mt.a ../../../libevm/libevm.dylib ../../../libethcore/libethcore.dylib ../../../libevmcore/libevmcore.dylib ../../../libp2p/libp2p.dylib /usr/local/lib/libminiupnpc.dylib ../../../libdevcrypto/libdevcrypto.dylib ../../../libdevcore/libdevcore.dylib /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libleveldb.dylib ../../../utils/libscrypt/libscrypt.dylib ../../../utils/secp256k1/libsecp256k1.a /usr/local/lib/libgmp.dylib ../../../evmjit/libevmjit/libevmjit.0.9.0.2.dylib ../../../libethash-cl/libethash-cl.dylib ../../../libethash/libethash.dylib /usr/local/lib/libcryptopp.dylib -framework OpenCL
[ 90%] Built target testeth
make: *** [all] Error 2
```

**Comment by hynese** [comment] 2017-12-21 11:19
`brew install cpp-ethereum`
```
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/ehyne/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0 -DCMAKE_BUILD_TYPE=Release -DCMAK
Last 15 lines from /Users/ehyne/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.173/750fb1d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:103 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20171221-72069-5hdbh2/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
```

**Comment by yuji-for-co** [comment] 2018-01-02 15:47
Below information from Ethereum Homestead Documentation is the cause I guess

OS X Homebrew packages
We generate Homebrew packages within our automated build system for the following OS X / Mac versions:

OS X Mavericks (10.9)
OS X Yosemite (10.10)
OS X El Capitan (10.11)
We only support 64-bit builds.

If your system does not support these OS X versions then you are out of luck. Sorry!

**Comment by phpid** [comment] 2018-01-02 15:55
macOS Sierra 10.12 has been released in September 2016, 15 months ago. Installation of cpp-ethereum is clearly broken.

I switched to https://github.com/ethereum-mining/ethminer which supports GPU mining and works fine on 10.12 & 10.13.

**Comment by DaveLindberg** [comment] 2018-01-30 15:26
Ethereum Wallet v0.9.3, available directly from Ethereum.org, is working correctly on MacOS

**Comment by krischik** [comment] 2018-02-08 07:10
> OS X Mavericks (10.9)
> OS X Yosemite (10.10)
> OS X El Capitan (10.11)

We are now at OS X High sierra (10.13) — so the mac version of cpp-ethereum is abandonware

@DaveLindberg but we are looking for the mining software not the wallet.

**Closed** 2018-03-23 10:08 UTC
