### ISSUE TITLE
Feature request: Install Solidity Only via Brew

### ISSUE THREAD

**Issue by VoR0220** [ethereum/homebrew-ethereum#42] opened 2015-10-23 19:59 UTC
I know this has been requested previously, but now it seems doable with the libweb3core libs now available. I continue to receive errors while trying to install cpp-ethereum via brew and I'm not sure how to proceed from here. Will post error separately, but I think that future issues would be mitigated by merely allowing people to simply download only solidity.

**Comment by dreid93** [comment] 2016-01-10 18:58
@VoR0220 if you just want `solc` you can use the Node.js version via `npm install -g solc`. 

I also support breaking up the cpp-ethereum formula into multiple packages. This will allow for it to be more module, and problems can be addressed on a formula by formula basis.

**Comment by bobsummerwill** [comment] 2016-01-12 06:38
This is a dupe of the older #31 issue logged by @jorisbontje.
Please can we close one of these, @chriseth?   Thanks!

Also, in terms of wanting this functionality ONLY because the brew formulas were a bit knackered, well, we should just keep them working.

There is a PR on libethereum created by @chfast  - https://github.com/ethereum/libethereum/pull/40 - talking about pulling EVM-related components out of libethereum to minimize dependencies for solidity, which @chriseth is not keen on.

I think it does make sense to try to decouple solidity from webthree, though - both within a homebrew/apt/installation sense, and at the repository level for git.    Not quite sure what form this would best take, though.

**Comment by caktux** [comment] 2016-01-15 00:06
solc already has its own package with apt unless that changed, it was when I was still maintaining cpp builds. It's not as easy with Homebrew, as the same build process cannot yield two different packages in the same way, so it will need it's own `solc.rb` or `solidity.rb` formula, and cpp-ethereum will have to disable compilation of it to prevent conflicts.

**Comment by bobsummerwill** [comment] 2016-02-25 01:25
Moved to https://github.com/ethereum/webthree-umbrella/issues/266.

**Closed by bobsummerwill** 2016-02-25 01:25 UTC
Labels: enhancement
