### ISSUE TITLE
failed to install on mac os high 10.13.3 for go

### ISSUE THREAD

**Issue by sravanthbaratam** [ethereum/homebrew-ethereum#154] opened 2018-03-19 04:14 UTC
```Sravanths-MacBook-Pro:~ sravanthbaratam$ brew install ethereum

==> Installing ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Users/sravanthbaratam/Library/Caches/Homebrew/ethereum--git
==> Checking out tag v1.8.2
==> go env
==> make all
Last 15 lines from /Users/sravanthbaratam/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/core
github.com/ethereum/go-ethereum/core/asm
github.com/ethereum/go-ethereum/whisper/whisperv6
github.com/ethereum/go-ethereum/cmd/evm/internal/compiler
github.com/ethereum/go-ethereum/p2p/protocols
github.com/ethereum/go-ethereum/whisper/shhclient
github.com/ethereum/go-ethereum/eth/filters
github.com/ethereum/go-ethereum/core/vm/runtime
github.com/ethereum/go-ethereum/light
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/miner
util.go:45: exit status 2
exit status 1
make: *** [all] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Install all go-ethereum executables https://github.com/ethereum/homebrew-ethereum/pull/114
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
Error While Installation of cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/133
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124
Error installing cpp-ethereum on OSX https://github.com/ethereum/homebrew-ethereum/issues/126
Mining on MacBookPro issue with cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/111
MAC: installation error for  brew install ethereum https://github.com/ethereum/homebrew-ethereum/issues/131
cpp-ethereum OSX build failed: Install clang 4+ from Homebrew https://github.com/ethereum/homebrew-ethereum/issues/127
Error installing go-ethereum on Mac OS X https://github.com/ethereum/homebrew-ethereum/issues/117
Mac OS X 10.12.5 install error for cpp-ethereum https://github.com/ethereum/homebrew-ethereum/issues/120
"util.go:45: exit status 2 exit status 1 make: *** [all] Error 1" when executing brew install ethereum on El Capitan https://github.com/ethereum/homebrew-ethereum/issues/132
cpp-ethereum issue on mac: CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message): https://github.com/ethereum/homebrew-ethereum/issues/129```

**Comment by axic** [comment] 2018-03-23 10:13
Duplicate of #117.

**Closed by axic** 2018-03-23 10:13 UTC
