### ISSUE TITLE
error: brew install cpp-ethereum with os x el capitan

### ISSUE THREAD

**Issue by code1628** [ethereum/homebrew-ethereum#41] opened 2015-10-16 19:17 UTC
/usr/local/include/jsonrpccpp/common/jsonparser.h:13:10: fatal error: 'jsoncpp/json/json.h' file not found
#include <jsoncpp/json/json.h>

==> Updating brew
$ brew update
Already up-to-date.

==> Installing eth
$ brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PR
==> make returns error above

any hint on how to resolve?

**Comment by code1628** [comment] 2015-10-16 22:31
i had to create by hand the jsoncpp directory and populate it to get past the build issue above.

**Comment by debris** [comment] 2015-10-19 02:53
I can't reproduce this issue on my machine 
- `yosemite 10.10.3`
- `libjson-rpc-cpp: stable 0.5.0 (bottled)`
- `jsoncpp: stable 0.10.5 (bottled), HEAD`).

 The error comes from [libjson-rpc-cpp](https://github.com/cinemast/libjson-rpc-cpp). It looks like you have outdated version of [jsoncpp](https://github.com/open-source-parsers/jsoncpp) or [libjson-rpc-cpp](https://github.com/cinemast/libjson-rpc-cpp).

**Comment by code1628** [comment] 2015-10-19 19:43
error persists even after forcing removal of previous versions and fresh install, see below:

$bash <(curl https://install-eth.ethereum.org -L)

==> Checking dependencies
 ✓  OS X Version 10.11
 ✓  git version 2.3.8 (Apple Git-58)
 ✓  Ruby 2.0.0
 ✓  Homebrew 0.9.5 (git revision 3c9da0; last commit 2015-10-19)

$brew info jsoncpp
jsoncpp: stable 0.10.5 (bottled), HEAD
Library for interacting with JSON
https://github.com/open-source-parsers/jsoncpp
/usr/local/Cellar/jsoncpp/0.10.5 (20 files, 640K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/jsoncpp.rb
==> Dependencies
Build: cmake ✔

$brew info libjson-rpc-cpp
libjson-rpc-cpp: stable 0.5.0 (bottled)
C++ framework for json-rpc
https://github.com/cinemast/libjson-rpc-cpp
/usr/local/Cellar/libjson-rpc-cpp/0.5.0 (30 files, 496K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libjson-rpc-cpp.rb
==> Dependencies
Build: cmake ✔
Required: argtable ✔, jsoncpp ✔, libmicrohttpd ✔

**Comment by debris** [comment] 2015-10-20 02:52
Ok, I reproduced your issue. I had to uninstall the libraries and install them again... It looks like homebrew added bottles for all libs recently and some of these bottles are prepared incorrectly. eg. `libjson-rpc-cpp`. To fix your issue please do:

```
brew uninstall libjson-rpc-cpp
brew install --build-from-source libjson-rpc-cpp
```

then just `brew install cpp-ethereum`

**Comment by code1628** [comment] 2015-10-20 13:29
Thanks!  The instructions above allow the compilation to complete but still fails on install with following message:

==> make install
Error: No such file or directory - test/testeth

**Comment by debris** [comment] 2015-10-27 04:40
should be fixed in next build

**Closed by debris** 2015-10-27 04:40 UTC
